# the blog that will read and publish asks
username: <%= ENV['TUMBLR_BOT_USERNAME'] %>
# the amount of asks to get with every request
ask_get_limit: 6
# the minimum amount of senteces to reply to an ask with
ask_min_sentences: 1
# the maximum amount of senteces to reply to an ask with
ask_max_sentences: 2
# the amount of randomness for marky_markov.  1 is incoherent, 2 is a little better, and values higher than 3 tend to just return unmodified centences
reply_randomness: 2

# how many asks the bot should look back on to evaluate its mental state
emotional_memory: 10
