consumer_key: <%= ENV['TUMBLR_CONSUMER_KEY'] %>
consumer_secret: <%= ENV['TUMBLR_CONSUMER_SECRET'] %>
oauth_token: <%= ENV['TUMBLR_OAUTH_TOKEN'] %>
oauth_secret: <%= ENV['TUMBLR_OAUTH_TOKEN_SECRET'] %>
              
